export const BLOCKED_ISPS = [
  '2day telecom llp',
  '365 - midlar ehf',
  '50hertz transmission gmbh',
  '6kanet',
  'adenis sarl',
  'ahbr company limited',
  'akamai international b.v.',
  'akamai technologies, inc.',
  'alastyr telekomunikasyon internet bilgisayar hizmetleri sanayi ticaret limited sirket',
  'alltele allmanna svenska telefonaktiebolaget',
  'alpari limited',
  'alvotech gmbh',
  'ankara universitesi rektorlugu',
  'arax i.s.p.',
  'as for mk netzdienste gmbh co. kg',
  'asiatech data transfer inc. plc',
  'asmunda new media ltd.',
  'aspire technology solutions ltd',
  'autonomous system for',
  'avea iletisim hizmetleri a.s.',
  'azeronline information services',
  'baharan plc',
  'baksell ltd llc',
  'beijing founder broadband network technology co. ltd',
  'beijing gehua catv network co. ltd.',
  'beijing kuandaitong telecom technology co. ltd',
  'belgacom s.a.',
  'british sky broadcasting limited',
  'broadnet as',
  'cableuropa s.a.u.',
  'call u communications ltd.',
  'camelhost sia',
  'cect-chinacomm communications co. ltd.',
  'china education and research network',
  'china internet network infomation center',
  'china telecom europe ltd.',
  'china unicom heilongjiang province network',
  'china unicom neimenggu province network',
  'chinanet beijing province network',
  'chinanet fujian province network',
  'chinanet guangdong province network',
  'chinanet guizhou province network',
  'chinanet henan province network',
  'chinanet neimenggu province network',
  'chinanet ningxia province network',
  'chinanet shaanxi province network',
  'chinanet shanxi province network',
  'chinanet',
  'chunghwa telecom data communication business group',
  'cipherspace gmbh',
  'amazon',
  'google',
  'microsoft',
  'cloudflare',
  'digitalocean',
  'linode',
  'ovh',
  'hetzner',
  'contabo',
  'vultr',
  'ibm',
  'oracle',
  'alibaba',
  'level 3',
  'leaseweb',
  'rackspace',
  'softlayer',
  'quadranet',
  'choopa',
  'colocrossing',
  'godaddy',
  'namecheap',
  'hostgator',
  'bluehost',
  'liquid web',
  'm247',
  'vpn',
  'proxy',
  'tor',
  'datacenter',
  'hosting',
  'cloud',
  'aruba',
].map(isp => isp.toLowerCase());